// Auth Type
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const TEMP_SET_USER = 'TEMP_SET_USER';

// Contents Type
export const LOAD_HOME_REQUEST = 'LOAD_HOME_REQUEST';
export const LOAD_HOME_SUCCESS = 'LOAD_HOME_SUCCESS';
export const LOAD_HOME_FAILURE = 'LOAD_HOME_FAILURE';

export const LOAD_TV_REQUEST = 'LOAD_TV_REQUEST';
export const LOAD_TV_SUCCESS = 'LOAD_TV_SUCCESS';
export const LOAD_TV_FAILURE = 'LOAD_TV_FAILURE';

export const LOAD_MOVIE_REQUEST = 'LOAD_MOVIE_REQUEST';
export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';
export const LOAD_MOVIE_FAILURE = 'LOAD_MOVIE_FAILURE';

export const GET_RANDOM_REQUEST = 'GET_RANDOM_REQUEST';
export const GET_RANDOM_SUCCESS = 'GET_RANDOM_SUCCESS';
export const GET_RANDOM_FAILURE = 'GET_RANDOM_FAILURE';

export const LOAD_DETAIL_REQUEST = 'LOAD_DETAIL_REQUEST';
export const LOAD_DETAIL_SUCCESS = 'LOAD_DETAIL_SUCCESS';
export const LOAD_DETAIL_FAILURE = 'LOAD_DETAIL_FAILURE';

export const LOAD_SIMILAR_REQUEST = 'LOAD_SIMILAR_REQUEST';
export const LOAD_SIMILAR_SUCCESS = 'LOAD_SIMILAR_SUCCESS';
export const LOAD_SIMILAR_FAILURE = 'LOAD_SIMILAR_FAILURE';

export const LOAD_SEASON_REQUEST = 'LOAD_SEASON_REQUEST';
export const LOAD_SEASON_SUCCESS = 'LOAD_SEASON_SUCCESS';
export const LOAD_SEASON_FAILURE = 'LOAD_SEASON_FAILURE';

export const CLEAR_DETAIL = 'CLEAR_DETAIL';
export const CHANGE_SEASON_NUMBER = 'CHANGE_SEASON_NUMBER';
